export const EXERCICIOS_DISPONIVEIS = [
  'Supino Reto',
  'Supino Inclinado',
  'Supino com Halteres',
  'Crucifixo',
  'Agachamento Livre',
  'Agachamento com Peso',
  'Agachamento Búlgaro',
  'Agachamento Pulo',
  'Leg Press',
  'Cadeira Extensora',
  'Cadeira Flexora',
  'Stiff',
  'Panturrilha',
  'Desenvolvimento Militar',
  'Elevação Lateral',
  'Elevação Frontal',
  'Remada Curvada',
  'Remada',
  'Puxada Frontal',
  'Barra Fixa',
  'Pull-ups',
  'Rosca Direta',
  'Rosca Martelo',
  'Rosca Scott',
  'Tríceps Corda',
  'Tríceps Testa',
  'Tríceps Francês',
  'Abdominal Infra',
  'Abdominal',
  'Prancha',
  'Mountain Climber',
  'Burpees',
  'Flexão de Braço',
  'Polichinelo',
  'Saltos',
  'Sprints',
  'Corda',
  'Box Jumps',
  'Power Clean',
  'Snatch',
  'Deadlift',
  'Cardio: Esteira (moderado)',
  'Cardio: Esteira (intervalado)',
  'Cardio: Bicicleta (intenso)',
  'Cardio: Elíptico (moderado)',
  'Cardio: Remo (intenso)',
  'Cardio: Caminhada (leve)',
  'Caminhada Leve',
  'Caminhada Moderada',
  'Caminhada Rápida',
  'Pedalada Leve',
  'Pedalada Moderada',
  'Pedalada Intensa',
  'Pedalada em Subida',
  'Alongamento de Pernas',
  'Alongamento de Braços',
  'Alongamento de Costas',
  'Alongamento de Tronco',
  'Respiração Profunda'
]

export const MUSCLE_WIKI_LINKS = {
  'Supino Reto': 'https://musclewiki.com/pt-br/exercises/bench-press',
  'Supino Inclinado': 'https://musclewiki.com/pt-br/exercises/incline-bench-press',
  'Supino com Halteres': 'https://musclewiki.com/pt-br/exercises/dumbbell-bench-press',
  'Crucifixo': 'https://musclewiki.com/pt-br/exercises/dumbbell-fly',
  'Agachamento Livre': 'https://musclewiki.com/pt-br/exercises/barbell-squat',
  'Agachamento com Peso': 'https://musclewiki.com/pt-br/exercises/barbell-squat',
  'Agachamento Búlgaro': 'https://musclewiki.com/pt-br/exercises/bulgarian-split-squat',
  'Agachamento Pulo': 'https://musclewiki.com/pt-br/exercises/jump-squat',
  'Leg Press': 'https://musclewiki.com/pt-br/exercises/leg-press',
  'Cadeira Extensora': 'https://musclewiki.com/pt-br/exercises/leg-extension',
  'Cadeira Flexora': 'https://musclewiki.com/pt-br/exercises/leg-curl',
  'Stiff': 'https://musclewiki.com/pt-br/exercises/romanian-deadlift',
  'Panturrilha': 'https://musclewiki.com/pt-br/exercises/calf-raise',
  'Desenvolvimento Militar': 'https://musclewiki.com/pt-br/exercises/overhead-press',
  'Elevação Lateral': 'https://musclewiki.com/pt-br/exercises/lateral-raise',
  'Elevação Frontal': 'https://musclewiki.com/pt-br/exercises/front-raise',
  'Remada Curvada': 'https://musclewiki.com/pt-br/exercises/barbell-row',
  'Remada': 'https://musclewiki.com/pt-br/exercises/barbell-row',
  'Puxada Frontal': 'https://musclewiki.com/pt-br/exercises/lat-pulldown',
  'Barra Fixa': 'https://musclewiki.com/pt-br/exercises/pull-up',
  'Pull-ups': 'https://musclewiki.com/pt-br/exercises/pull-up',
  'Rosca Direta': 'https://musclewiki.com/pt-br/exercises/barbell-curl',
  'Rosca Martelo': 'https://musclewiki.com/pt-br/exercises/hammer-curl',
  'Rosca Scott': 'https://musclewiki.com/pt-br/exercises/preacher-curl',
  'Tríceps Corda': 'https://musclewiki.com/pt-br/exercises/tricep-pushdown',
  'Tríceps Testa': 'https://musclewiki.com/pt-br/exercises/skull-crushers',
  'Tríceps Francês': 'https://musclewiki.com/pt-br/exercises/tricep-extension',
  'Abdominal Infra': 'https://musclewiki.com/pt-br/exercises/crunch',
  'Abdominal': 'https://musclewiki.com/pt-br/exercises/crunch',
  'Prancha': 'https://musclewiki.com/pt-br/exercises/plank',
  'Mountain Climber': 'https://musclewiki.com/pt-br/exercises/mountain-climber',
  'Burpees': 'https://musclewiki.com/pt-br/exercises/burpee',
  'Flexão de Braço': 'https://musclewiki.com/pt-br/exercises/push-up',
  'Polichinelo': 'https://musclewiki.com/pt-br/exercises/jumping-jack',
  'Saltos': 'https://musclewiki.com/pt-br/exercises/box-jump',
  'Sprints': 'https://musclewiki.com/pt-br/exercises/sprint',
  'Corda': 'https://musclewiki.com/pt-br/exercises/jump-rope',
  'Box Jumps': 'https://musclewiki.com/pt-br/exercises/box-jump',
  'Power Clean': 'https://musclewiki.com/pt-br/exercises/power-clean',
  'Snatch': 'https://musclewiki.com/pt-br/exercises/snatch',
  'Deadlift': 'https://musclewiki.com/pt-br/exercises/deadlift'
}

export const MUSCLE_IMAGES = {
  'Supino Reto': 'https://musclewiki.com/static/muscles/pectoralis-major.png',
  'Supino Inclinado': 'https://musclewiki.com/static/muscles/pectoralis-major.png',
  'Supino com Halteres': 'https://musclewiki.com/static/muscles/pectoralis-major.png',
  'Crucifixo': 'https://musclewiki.com/static/muscles/pectoralis-major.png',
  'Agachamento Livre': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Agachamento com Peso': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Agachamento Búlgaro': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Agachamento Pulo': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Leg Press': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Cadeira Extensora': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Cadeira Flexora': 'https://musclewiki.com/static/muscles/hamstrings.png',
  'Stiff': 'https://musclewiki.com/static/muscles/hamstrings.png',
  'Panturrilha': 'https://musclewiki.com/static/muscles/gastrocnemius.png',
  'Desenvolvimento Militar': 'https://musclewiki.com/static/muscles/deltoid.png',
  'Elevação Lateral': 'https://musclewiki.com/static/muscles/deltoid.png',
  'Elevação Frontal': 'https://musclewiki.com/static/muscles/deltoid.png',
  'Remada Curvada': 'https://musclewiki.com/static/muscles/latissimus-dorsi.png',
  'Remada': 'https://musclewiki.com/static/muscles/latissimus-dorsi.png',
  'Puxada Frontal': 'https://musclewiki.com/static/muscles/latissimus-dorsi.png',
  'Barra Fixa': 'https://musclewiki.com/static/muscles/latissimus-dorsi.png',
  'Pull-ups': 'https://musclewiki.com/static/muscles/latissimus-dorsi.png',
  'Rosca Direta': 'https://musclewiki.com/static/muscles/biceps-brachii.png',
  'Rosca Martelo': 'https://musclewiki.com/static/muscles/brachialis.png',
  'Rosca Scott': 'https://musclewiki.com/static/muscles/biceps-brachii.png',
  'Tríceps Corda': 'https://musclewiki.com/static/muscles/triceps-brachii.png',
  'Tríceps Testa': 'https://musclewiki.com/static/muscles/triceps-brachii.png',
  'Tríceps Francês': 'https://musclewiki.com/static/muscles/triceps-brachii.png',
  'Abdominal Infra': 'https://musclewiki.com/static/muscles/rectus-abdominis.png',
  'Abdominal': 'https://musclewiki.com/static/muscles/rectus-abdominis.png',
  'Prancha': 'https://musclewiki.com/static/muscles/rectus-abdominis.png',
  'Mountain Climber': 'https://musclewiki.com/static/muscles/rectus-abdominis.png',
  'Burpees': 'https://musclewiki.com/static/muscles/rectus-abdominis.png',
  'Flexão de Braço': 'https://musclewiki.com/static/muscles/pectoralis-major.png',
  'Polichinelo': 'https://musclewiki.com/static/muscles/rectus-abdominis.png',
  'Saltos': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Sprints': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Corda': 'https://musclewiki.com/static/muscles/gastrocnemius.png',
  'Box Jumps': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Power Clean': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Snatch': 'https://musclewiki.com/static/muscles/quadriceps.png',
  'Deadlift': 'https://musclewiki.com/static/muscles/erector-spinae.png'
}

export const TREINOS_POR_OBJETIVO = {
  massa: {
    nome: 'Ganho de Massa',
    descricao: 'Treino focado em hipertrofia muscular com cargas moderadas a altas',
    duracao: 50,
    descanso: 90,
    intervalo: 120,
    exercicios: [
      { nome: 'Supino Reto', series: 4, repeticoes: '8-12', descanso: 90 },
      { nome: 'Agachamento Livre', series: 4, repeticoes: '8-12', descanso: 120 },
      { nome: 'Desenvolvimento Militar', series: 3, repeticoes: '10-12', descanso: 60 },
      { nome: 'Barra Fixa', series: 3, repeticoes: '8-10', descanso: 90 },
      { nome: 'Remada Curvada', series: 4, repeticoes: '10-12', descanso: 90 },
      { nome: 'Rosca Direta', series: 3, repeticoes: '10-12', descanso: 60 },
      { nome: 'Leg Press', series: 4, repeticoes: '10-12', descanso: 90 },
      { nome: 'Cardio: Esteira (moderado)', series: 1, repeticoes: '10 min', descanso: 0 }
    ]
  },
  peso: {
    nome: 'Perda de Peso',
    descricao: 'Treino combinado HIIT + musculação para queima calórica',
    duracao: 45,
    descanso: 60,
    intervalo: 30,
    exercicios: [
      { nome: 'HIIT: Polichinelo', series: 3, repeticoes: '45s', descanso: 15 },
      { nome: 'Agachamento com Peso', series: 3, repeticoes: '15-20', descanso: 45 },
      { nome: 'HIIT: Mountain Climber', series: 3, repeticoes: '30s', descanso: 15 },
      { nome: 'Supino com Halteres', series: 3, repeticoes: '12-15', descanso: 45 },
      { nome: 'HIIT: Saltos', series: 3, repeticoes: '30s', descanso: 15 },
      { nome: 'Leg Press', series: 3, repeticoes: '15-20', descanso: 60 },
      { nome: 'HIIT: Corrida no lugar', series: 2, repeticoes: '45s', descanso: 15 },
      { nome: 'Cardio: Bicicleta (intenso)', series: 1, repeticoes: '15 min', descanso: 0 }
    ]
  },
  tonificacao: {
    nome: 'Tonificação',
    descricao: 'Treino com repetições moderadas para definição muscular',
    duracao: 40,
    descanso: 45,
    intervalo: 60,
    exercicios: [
      { nome: 'Supino Inclinado', series: 3, repeticoes: '12-15', descanso: 45 },
      { nome: 'Agachamento Búlgaro', series: 3, repeticoes: '12-15', descanso: 45 },
      { nome: 'Elevação Lateral', series: 3, repeticoes: '15-20', descanso: 30 },
      { nome: 'HIIT: Corrida no lugar', series: 2, repeticoes: '45s', descanso: 15 },
      { nome: 'Abdominal Infra', series: 3, repeticoes: '15-20', descanso: 30 },
      { nome: 'Rosca Direta', series: 3, repeticoes: '12-15', descanso: 45 },
      { nome: 'Prancha', series: 3, repeticoes: '30s', descanso: 30 },
      { nome: 'Cardio: Elíptico (moderado)', series: 1, repeticoes: '12 min', descanso: 0 }
    ]
  },
  gordura: {
    nome: 'Queima de Gordura',
    descricao: 'Treino intenso com foco em HIIT para queima de gordura',
    duracao: 35,
    descanso: 30,
    intervalo: 20,
    exercicios: [
      { nome: 'HIIT: Sprint', series: 4, repeticoes: '30s', descanso: 30 },
      { nome: 'Agachamento Pulo', series: 3, repeticoes: '15', descanso: 30 },
      { nome: 'HIIT: Burpees', series: 3, repeticoes: '30s', descanso: 20 },
      { nome: 'Flexão de Braço', series: 3, repeticoes: '15-20', descanso: 30 },
      { nome: 'HIIT: Corda', series: 3, repeticoes: '45s', descanso: 20 },
      { nome: 'Prancha', series: 3, repeticoes: '45s', descanso: 20 },
      { nome: 'HIIT: Mountain Climber', series: 3, repeticoes: '30s', descanso: 20 },
      { nome: 'Cardio: Esteira (intervalado)', series: 1, repeticoes: '20 min', descanso: 0 }
    ]
  },
  performance: {
    nome: 'Alta Performance',
    descricao: 'Treino avançado para atletas com alta intensidade',
    duracao: 55,
    descanso: 120,
    intervalo: 90,
    exercicios: [
      { nome: 'Power Clean', series: 4, repeticoes: '6-8', descanso: 120 },
      { nome: 'Snatch', series: 3, repeticoes: '4-6', descanso: 180 },
      { nome: 'HIIT: Sprints', series: 5, repeticoes: '20s', descanso: 40 },
      { nome: 'Agachamento Pesado', series: 5, repeticoes: '5-8', descanso: 150 },
      { nome: 'Deadlift', series: 4, repeticoes: '5-8', descanso: 180 },
      { nome: 'HIIT: Box Jumps', series: 4, repeticoes: '10', descanso: 60 },
      { nome: 'Pull-ups', series: 3, repeticoes: '8-12', descanso: 90 },
      { nome: 'Cardio: Remo (intenso)', series: 1, repeticoes: '10 min', descanso: 0 }
    ]
  },
  manutencao: {
    nome: 'Manutenção',
    descricao: 'Treino equilibrado para manter condicionamento físico',
    duracao: 45,
    descanso: 60,
    intervalo: 60,
    exercicios: [
      { nome: 'Supino Reto', series: 3, repeticoes: '10-12', descanso: 60 },
      { nome: 'Agachamento', series: 3, repeticoes: '12-15', descanso: 60 },
      { nome: 'HIIT: Corda', series: 2, repeticoes: '30s', descanso: 30 },
      { nome: 'Remada', series: 3, repeticoes: '12-15', descanso: 60 },
      { nome: 'HIIT: Polichinelo', series: 2, repeticoes: '30s', descanso: 30 },
      { nome: 'Abdominal', series: 3, repeticoes: '15-20', descanso: 45 },
      { nome: 'Rosca Direta', series: 3, repeticoes: '12-15', descanso: 45 },
      { nome: 'Cardio: Caminhada (leve)', series: 1, repeticoes: '15 min', descanso: 0 }
    ]
  },
  caminhada: {
    nome: 'Caminhada',
    descricao: 'Programa de caminhada para saúde cardiovascular e bem-estar',
    duracao: 40,
    descanso: 0,
    intervalo: 0,
    exercicios: [
      { nome: 'Aquecimento: Caminhada Leve', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Caminhada Moderada', series: 1, repeticoes: '15 min', descanso: 0 },
      { nome: 'Caminhada Rápida', series: 1, repeticoes: '10 min', descanso: 0 },
      { nome: 'Alongamento de Pernas', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Alongamento de Braços', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Alongamento de Costas', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Respiração Profunda', series: 1, repeticoes: '3 min', descanso: 0 },
      { nome: 'Caminhada Leve (Resfriamento)', series: 1, repeticoes: '5 min', descanso: 0 }
    ]
  },
  pedalada: {
    nome: 'Pedalada',
    descricao: 'Programa de pedalada para condicionamento cardiovascular',
    duracao: 45,
    descanso: 0,
    intervalo: 0,
    exercicios: [
      { nome: 'Aquecimento: Pedalada Leve', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Pedalada Moderada', series: 1, repeticoes: '15 min', descanso: 0 },
      { nome: 'Pedalada Intensa', series: 1, repeticoes: '10 min', descanso: 0 },
      { nome: 'Pedalada em Subida', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Pedalada Moderada', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Alongamento de Pernas', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Alongamento de Tronco', series: 1, repeticoes: '5 min', descanso: 0 },
      { nome: 'Pedalada Leve (Resfriamento)', series: 1, repeticoes: '5 min', descanso: 0 }
    ]
  }
}

export const DIAS_LABEL = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']
